
export const Dimensions = {
  APP_BAR_HEIGHT_PX: 64,
  SIDE_BAR_WIDTH_PX: 300
};

export const Times = {
  NAVIGATION_DELAY_MS: 350,
  RESIZE_THROTTLE_MS: 500,
  SECONDS_PER_MIN: 60,
  DEFAULT_DELAY_SECONDS: 0
};
